import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import FaviconHandler from "./components/FaviconHandler";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/Q Black.svg", // Default favicon (fallback)
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <FaviconHandler />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
